# Generated by Django 5.2.7 on 2025-10-22 00:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('user_login', 'Foydalanuvchi tizimga kirdi'), ('user_logout', 'Foydalanuvchi tizimdan chiqdi'), ('user_created', 'Yangi foydalanuvchi yaratildi'), ('user_updated', "Foydalanuvchi ma'lumotlari yangilandi"), ('user_deleted', "Foydalanuvchi o'chirildi"), ('user_status_changed', "Foydalanuvchi holati o'zgartirildi"), ('class_created', 'Yangi sinf yaratildi'), ('class_updated', "Sinf ma'lumotlari yangilandi"), ('class_deleted', "Sinf o'chirildi"), ('subject_created', 'Yangi fan yaratildi'), ('subject_updated', "Fan ma'lumotlari yangilandi"), ('subject_deleted', "Fan o'chirildi"), ('announcement_created', "Yangi e'lon yaratildi"), ('announcement_updated', "E'lon yangilandi"), ('announcement_deleted', "E'lon o'chirildi"), ('schedule_updated', 'Dars jadvali yangilandi'), ('report_generated', 'Hisobot yaratildi')], max_length=50)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Faoliyat tarixi',
                'verbose_name_plural': 'Faoliyat tarixi',
                'ordering': ['-created_at'],
            },
        ),
    ]
