# Generated by Django 5.2.7 on 2025-10-22 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_activitylog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'verbose_name': 'Dars jadvali', 'verbose_name_plural': 'Dars jadvali'},
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='lesson_number',
        ),
        migrations.AddField(
            model_name='schedule',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Izohlar'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='period',
            field=models.IntegerField(choices=[(1, '1-dars'), (2, '2-dars'), (3, '3-dars'), (4, '4-dars'), (5, '5-dars'), (6, '6-dars')], default=1, verbose_name='Dars raqami'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='room',
            field=models.CharField(default=1, max_length=20, verbose_name='Xona'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='schedule',
            name='day',
            field=models.CharField(choices=[('monday', 'Dushanba'), ('tuesday', 'Seshanba'), ('wednesday', 'Chorshanba'), ('thursday', 'Payshanba'), ('friday', 'Juma'), ('saturday', 'Shanba')], max_length=20, verbose_name='Hafta kuni'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='school_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.schoolclass', verbose_name='Sinf'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.subject', verbose_name='Fan'),
        ),
    ]
