# Generated by Django 5.2.7 on 2025-10-22 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_schedule_options_remove_schedule_lesson_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='period',
            field=models.IntegerField(choices=[(1, '1-dars'), (2, '2-dars'), (3, '3-dars'), (4, '4-dars'), (5, '5-dars'), (6, '6-dars'), (7, '7-dars'), (8, '8-dars')], default=1, verbose_name='Dars raqami'),
        ),
    ]
